package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntMortgages<M extends BaseEntMortgages<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_mortgages";

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 动产抵押-登记编号
	 */
	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	/**
	 * 动产抵押-登记编号
	 */
	public java.lang.String getNumber() {
		return get("number");
	}

	/**
	 * 动产抵押-登记日期
	 */
	public void setDate(java.lang.String date) {
		set("date", date);
	}

	/**
	 * 动产抵押-登记日期
	 */
	public java.lang.String getDate() {
		return get("date");
	}

	/**
	 * 动产抵押-状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	/**
	 * 动产抵押-状态
	 */
	public java.lang.String getStatus() {
		return get("status");
	}

	/**
	 * 动产抵押-登记机关
	 */
	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	/**
	 * 动产抵押-登记机关
	 */
	public java.lang.String getDepartment() {
		return get("department");
	}

	/**
	 * 动产抵押-被担保债权数额
	 */
	public void setAmount(java.lang.String amount) {
		set("amount", amount);
	}

	/**
	 * 动产抵押-被担保债权数额
	 */
	public java.lang.String getAmount() {
		return get("amount");
	}

	/**
	 * 动产抵押-被担保债权种类
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

	/**
	 * 动产抵押-被担保债权种类
	 */
	public java.lang.String getType() {
		return get("type");
	}

	/**
	 * 动产抵押-债务人履行债务的期限
	 */
	public void setPeriod(java.lang.String period) {
		set("period", period);
	}

	/**
	 * 动产抵押-债务人履行债务的期限
	 */
	public java.lang.String getPeriod() {
		return get("period");
	}

	/**
	 * 动产抵押-担保范围
	 */
	public void setScope(java.lang.String scope) {
		set("scope", scope);
	}

	/**
	 * 动产抵押-担保范围
	 */
	public java.lang.String getScope() {
		return get("scope");
	}

	/**
	 * 动产抵押-备注
	 */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	/**
	 * 动产抵押-备注
	 */
	public java.lang.String getRemarks() {
		return get("remarks");
	}

	/**
	 * 动产抵押-被担保债权概况-种类
	 */
	public void setDebitType(java.lang.String debitType) {
		set("debit_type", debitType);
	}

	/**
	 * 动产抵押-被担保债权概况-种类
	 */
	public java.lang.String getDebitType() {
		return get("debit_type");
	}

	/**
	 * 动产抵押-被担保债权概况-币种
	 */
	public void setDebitCurrency(java.lang.String debitCurrency) {
		set("debit_currency", debitCurrency);
	}

	/**
	 * 动产抵押-被担保债权概况-币种
	 */
	public java.lang.String getDebitCurrency() {
		return get("debit_currency");
	}

	/**
	 * 动产抵押-被担保债权概况-数额
	 */
	public void setDebitAmount(java.lang.String debitAmount) {
		set("debit_amount", debitAmount);
	}

	/**
	 * 动产抵押-被担保债权概况-数额
	 */
	public java.lang.String getDebitAmount() {
		return get("debit_amount");
	}

	/**
	 * 动产抵押-被担保债权概况-担保的范围
	 */
	public void setDebitScope(java.lang.String debitScope) {
		set("debit_scope", debitScope);
	}

	/**
	 * 动产抵押-被担保债权概况-担保的范围
	 */
	public java.lang.String getDebitScope() {
		return get("debit_scope");
	}

	/**
	 * 动产抵押-被担保债权概况-债务人履行债务的期限
	 */
	public void setDebitPeriod(java.lang.String debitPeriod) {
		set("debit_period", debitPeriod);
	}

	/**
	 * 动产抵押-被担保债权概况-债务人履行债务的期限
	 */
	public java.lang.String getDebitPeriod() {
		return get("debit_period");
	}

	/**
	 * 动产抵押-被担保债权概况-备注
	 */
	public void setDebitRemarks(java.lang.String debitRemarks) {
		set("debit_remarks", debitRemarks);
	}

	/**
	 * 动产抵押-被担保债权概况-备注
	 */
	public java.lang.String getDebitRemarks() {
		return get("debit_remarks");
	}

	/**
	 * 动产抵押-注销日期
	 */
	public void setCloseDate(java.lang.String closeDate) {
		set("close_date", closeDate);
	}

	/**
	 * 动产抵押-注销日期
	 */
	public java.lang.String getCloseDate() {
		return get("close_date");
	}

	/**
	 * 动产抵押-注销原因
	 */
	public void setCloseReason(java.lang.String closeReason) {
		set("close_reason", closeReason);
	}

	/**
	 * 动产抵押-注销原因
	 */
	public java.lang.String getCloseReason() {
		return get("close_reason");
	}

	/**
	 * 动产抵押-序号
	 */
	public void setSeqNo(java.lang.String seqNo) {
		set("seq_no", seqNo);
	}

	/**
	 * 动产抵押-序号
	 */
	public java.lang.String getSeqNo() {
		return get("seq_no");
	}

	/**
	 * 动产抵押-抵押物备注
	 */
	public void setRemarksGoods(java.lang.String remarksGoods) {
		set("remarks_goods", remarksGoods);
	}

	/**
	 * 动产抵押-抵押物备注
	 */
	public java.lang.String getRemarksGoods() {
		return get("remarks_goods");
	}

	/**
	 * 动产抵押-抵押物所有权归属
	 */
	public void setBelongTo(java.lang.String belongTo) {
		set("belong_to", belongTo);
	}

	/**
	 * 动产抵押-抵押物所有权归属
	 */
	public java.lang.String getBelongTo() {
		return get("belong_to");
	}

	/**
	 * 动产抵押-抵押物名称
	 */
	public void setNameGoods(java.lang.String nameGoods) {
		set("name_goods", nameGoods);
	}

	/**
	 * 动产抵押-抵押物名称
	 */
	public java.lang.String getNameGoods() {
		return get("name_goods");
	}

	/**
	 * 动产抵押-抵押物描述
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

	/**
	 * 动产抵押-抵押物描述
	 */
	public java.lang.String getContent() {
		return get("content");
	}

	/**
	 * 动产抵押-抵押物序号
	 */
	public void setSeqGoods(java.lang.String seqGoods) {
		set("seq_goods", seqGoods);
	}

	/**
	 * 动产抵押-抵押物序号
	 */
	public java.lang.String getSeqGoods() {
		return get("seq_goods");
	}

	/**
	 * 动产抵押-抵押权人证照/证件号码
	 */
	public void setIdentifyNo(java.lang.String identifyNo) {
		set("identify_no", identifyNo);
	}

	/**
	 * 动产抵押-抵押权人证照/证件号码
	 */
	public java.lang.String getIdentifyNo() {
		return get("identify_no");
	}

	/**
	 * 动产抵押-抵押权人序号
	 */
	public void setSeqPerson(java.lang.String seqPerson) {
		set("seq_person", seqPerson);
	}

	/**
	 * 动产抵押-抵押权人序号
	 */
	public java.lang.String getSeqPerson() {
		return get("seq_person");
	}

	/**
	 * 动产抵押-抵押权人名称
	 */
	public void setNamePerson(java.lang.String namePerson) {
		set("name_person", namePerson);
	}

	/**
	 * 动产抵押-抵押权人名称
	 */
	public java.lang.String getNamePerson() {
		return get("name_person");
	}

	/**
	 * 动产抵押-抵押权人证照/证件类型
	 */
	public void setIdentifyType(java.lang.String identifyType) {
		set("identify_type", identifyType);
	}

	/**
	 * 动产抵押-抵押权人证照/证件类型
	 */
	public java.lang.String getIdentifyType() {
		return get("identify_type");
	}

}
