package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntPatent<M extends BaseEntPatent<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_patent";

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 专利详情-名称
	 */
	public void setPatentName(java.lang.String patentName) {
		set("patent_name", patentName);
	}

	/**
	 * 专利详情-名称
	 */
	public java.lang.String getPatentName() {
		return get("patent_name");
	}

	/**
	 * 专利详情-授权公告号
	 */
	public void setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
	}

	/**
	 * 专利详情-授权公告号
	 */
	public java.lang.String getTypeName() {
		return get("type_name");
	}

	/**
	 * 专利详情-授权公告号
	 */
	public void setOuthorNum(java.lang.String outhorNum) {
		set("outhor_num", outhorNum);
	}

	/**
	 * 专利详情-授权公告号
	 */
	public java.lang.String getOuthorNum() {
		return get("outhor_num");
	}

	/**
	 * 专利详情-申请号
	 */
	public void setRequestNum(java.lang.String requestNum) {
		set("request_num", requestNum);
	}

	/**
	 * 专利详情-申请号
	 */
	public java.lang.String getRequestNum() {
		return get("request_num");
	}

	/**
	 * 专利详情-摘要
	 */
	public void setBrief(java.lang.String brief) {
		set("brief", brief);
	}

	/**
	 * 专利详情-摘要
	 */
	public java.lang.String getBrief() {
		return get("brief");
	}

	/**
	 * 专利详情-授权公告日
	 */
	public void setOuthorDate(java.lang.String outhorDate) {
		set("outhor_date", outhorDate);
	}

	/**
	 * 专利详情-授权公告日
	 */
	public java.lang.String getOuthorDate() {
		return get("outhor_date");
	}

	/**
	 * 专利详情-申请日
	 */
	public void setRequestDate(java.lang.String requestDate) {
		set("request_date", requestDate);
	}

	/**
	 * 专利详情-申请日
	 */
	public java.lang.String getRequestDate() {
		return get("request_date");
	}

}
