package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntLaw<M extends BaseEntLaw<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_law";

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 法院裁判文书案号
	 */
	public void setCaseNo(java.lang.String caseNo) {
		set("case_no", caseNo);
	}

	/**
	 * 法院裁判文书案号
	 */
	public java.lang.String getCaseNo() {
		return get("case_no");
	}

	/**
	 * 法院裁判文书标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 法院裁判文书标题
	 */
	public java.lang.String getTitle() {
		return get("title");
	}

	/**
	 * 法院裁判文书发布日期
	 */
	public void setDate(java.lang.String date) {
		set("date", date);
	}

	/**
	 * 法院裁判文书发布日期
	 */
	public java.lang.String getDate() {
		return get("date");
	}

	/**
	 * 法院裁判文书类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}

	/**
	 * 法院裁判文书类型
	 */
	public java.lang.String getType() {
		return get("type");
	}

}
