package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatEventRoundTwo<M extends BaseStatEventRoundTwo<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stat_event_round_two";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 事件类型ID
	 */
	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}

	/**
	 * 事件类型ID
	 */
	public java.lang.Integer getTypeId() {
		return get("type_id");
	}

	/**
	 * 数量
	 */
	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	/**
	 * 数量
	 */
	public java.lang.Integer getCount() {
		return get("count");
	}

	/**
	 * 统计时间
	 */
	public void setCountDate(java.lang.String countDate) {
		set("count_date", countDate);
	}

	/**
	 * 统计时间
	 */
	public java.lang.String getCountDate() {
		return get("count_date");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
