package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntAdmin<M extends BaseEntAdmin<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_admin";

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 公司主要人员信息
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 公司主要人员信息
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 职位信息
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	/**
	 * 职位信息
	 */
	public java.lang.String getTitle() {
		return get("title");
	}

}
