package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRptStatTrendAll<M extends BaseRptStatTrendAll<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "rpt_stat_trend_all";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 私募
	 */
	public void setPe(java.lang.Double pe) {
		set("pe", pe);
	}

	/**
	 * 私募
	 */
	public java.lang.Double getPe() {
		return get("pe");
	}

	/**
	 * 券商
	 */
	public void setBroker(java.lang.Double broker) {
		set("broker", broker);
	}

	/**
	 * 券商
	 */
	public java.lang.Double getBroker() {
		return get("broker");
	}

	/**
	 * 资管
	 */
	public void setAm(java.lang.Double am) {
		set("am", am);
	}

	/**
	 * 资管
	 */
	public java.lang.Double getAm() {
		return get("am");
	}

	/**
	 * 信托
	 */
	public void setTrust(java.lang.Double trust) {
		set("trust", trust);
	}

	/**
	 * 信托
	 */
	public java.lang.Double getTrust() {
		return get("trust");
	}

	/**
	 * 银行
	 */
	public void setBank(java.lang.Double bank) {
		set("bank", bank);
	}

	/**
	 * 银行
	 */
	public java.lang.Double getBank() {
		return get("bank");
	}

	/**
	 * 保险
	 */
	public void setInsurance(java.lang.Double insurance) {
		set("insurance", insurance);
	}

	/**
	 * 保险
	 */
	public java.lang.Double getInsurance() {
		return get("insurance");
	}

	/**
	 * 协议转让
	 */
	public void setProTransfer(java.lang.Double proTransfer) {
		set("pro_transfer", proTransfer);
	}

	/**
	 * 协议转让
	 */
	public java.lang.Double getProTransfer() {
		return get("pro_transfer");
	}

	/**
	 * 发行股份购买
	 */
	public void setSharePurchase(java.lang.Double sharePurchase) {
		set("share_purchase", sharePurchase);
	}

	/**
	 * 发行股份购买
	 */
	public java.lang.Double getSharePurchase() {
		return get("share_purchase");
	}

	/**
	 * 增资
	 */
	public void setCapIncrease(java.lang.Double capIncrease) {
		set("cap_increase", capIncrease);
	}

	/**
	 * 增资
	 */
	public java.lang.Double getCapIncrease() {
		return get("cap_increase");
	}

	/**
	 * 对外投资
	 */
	public void setInvestment(java.lang.Double investment) {
		set("investment", investment);
	}

	/**
	 * 对外投资
	 */
	public java.lang.Double getInvestment() {
		return get("investment");
	}

	/**
	 * 股权类投资基金
	 */
	public void setStockFund(java.lang.Double stockFund) {
		set("stock_fund", stockFund);
	}

	/**
	 * 股权类投资基金
	 */
	public java.lang.Double getStockFund() {
		return get("stock_fund");
	}

	/**
	 * 创业类投资基金
	 */
	public void setStartFund(java.lang.Double startFund) {
		set("start_fund", startFund);
	}

	/**
	 * 创业类投资基金
	 */
	public java.lang.Double getStartFund() {
		return get("start_fund");
	}

	/**
	 * 投资事件
	 */
	public void setInvestEvents(java.lang.Double investEvents) {
		set("invest_events", investEvents);
	}

	/**
	 * 投资事件
	 */
	public java.lang.Double getInvestEvents() {
		return get("invest_events");
	}

	/**
	 * 退出事件
	 */
	public void setExitEvents(java.lang.Double exitEvents) {
		set("exit_events", exitEvents);
	}

	/**
	 * 退出事件
	 */
	public java.lang.Double getExitEvents() {
		return get("exit_events");
	}

	/**
	 * 统计时间
	 */
	public void setStatDate(java.lang.String statDate) {
		set("stat_date", statDate);
	}

	/**
	 * 统计时间
	 */
	public java.lang.String getStatDate() {
		return get("stat_date");
	}

	/**
	 * 创建日期
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建日期
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新日期
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新日期
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
