package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatDashboard<M extends BaseStatDashboard<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "stat_dashboard";

	/**
	 * 自增ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	/**
	 * 自增ID
	 */
	public java.lang.Integer getId() {
		return get("id");
	}

	/**
	 * 统计字段
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 统计字段
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 当日量
	 */
	public void setDailyCount(java.lang.Integer dailyCount) {
		set("daily_count", dailyCount);
	}

	/**
	 * 当日量
	 */
	public java.lang.Integer getDailyCount() {
		return get("daily_count");
	}

	/**
	 * 总量
	 */
	public void setTotal(java.lang.Integer total) {
		set("total", total);
	}

	/**
	 * 总量
	 */
	public java.lang.Integer getTotal() {
		return get("total");
	}

	/**
	 * 标准刻度值-低
	 */
	public void setStdMin(java.lang.Integer stdMin) {
		set("std_min", stdMin);
	}

	/**
	 * 标准刻度值-低
	 */
	public java.lang.Integer getStdMin() {
		return get("std_min");
	}

	/**
	 * 标准刻度值-中
	 */
	public void setStdMedian(java.lang.Integer stdMedian) {
		set("std_median", stdMedian);
	}

	/**
	 * 标准刻度值-中
	 */
	public java.lang.Integer getStdMedian() {
		return get("std_median");
	}

	/**
	 * 标准刻度值-高
	 */
	public void setStdMax(java.lang.Integer stdMax) {
		set("std_max", stdMax);
	}

	/**
	 * 标准刻度值-高
	 */
	public java.lang.Integer getStdMax() {
		return get("std_max");
	}

	/**
	 * 统计时间
	 */
	public void setCountDate(java.lang.String countDate) {
		set("count_date", countDate);
	}

	/**
	 * 统计时间
	 */
	public java.lang.String getCountDate() {
		return get("count_date");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
