package com.kd.model.general.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEntHolder<M extends BaseEntHolder<M>> extends Model<M> implements IBean {

	/**
	 * 表名
	 */
	public static final String TableName = "ent_holder";

	/**
	 * 企业UUID
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	/**
	 * 企业UUID
	 */
	public java.lang.String getUuid() {
		return get("uuid");
	}

	/**
	 * 股东名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

	/**
	 * 股东名称
	 */
	public java.lang.String getName() {
		return get("name");
	}

	/**
	 * 股东类型
	 */
	public void setStockType(java.lang.String stockType) {
		set("stock_type", stockType);
	}

	/**
	 * 股东类型
	 */
	public java.lang.String getStockType() {
		return get("stock_type");
	}

	/**
	 * 实缴出资情况（日期，额度）
	 */
	public void setRCapi(java.lang.String rCapi) {
		set("r_capi", rCapi);
	}

	/**
	 * 实缴出资情况（日期，额度）
	 */
	public java.lang.String getRCapi() {
		return get("r_capi");
	}

	/**
	 * 应缴出资情况（日期，额度）
	 */
	public void setSCapi(java.lang.String sCapi) {
		set("s_capi", sCapi);
	}

	/**
	 * 应缴出资情况（日期，额度）
	 */
	public java.lang.String getSCapi() {
		return get("s_capi");
	}

}
